sshclient:
  identity: "/Users/rlehmann/.minikube/machines/minikube/id_rsa"
  server: docker@127.0.0.1:58196
  known_hosts: "~/.ssh/known_hosts"
  insecure: false

tunnel:
  - remote: "172.17.0.100:80"
    local: "172.17.0.100:80"
    forward: yes
  - remote: "172.17.0.100:443"
    local: "172.17.0.100:443"
    forward: yes
